### ISSUE TITLE
Audio Glitchy, crispy.

### ISSUE THREAD

**Issue by Domxoxo** [vinegarhq/sober#855]
### Acknowledgement of checking existent issues

- [x] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Yes, i have checked other Issues and no this isnt adressed. Im on Ubuntu and heres my specs:

Processor : Intel Core i7-2600 @ 8x 3,8GHz
GPU : AMD Radeon Graphics 480 
16gb ram
Motherboard : P8H61-M PRO

this happens in every game I join, no. its not an audio issue of the OS itself, just Sober.

**Comment by jojgo** [comment]
Were you able to find a fix? I am experiencing the same issue whenever audio from the experience plays. It started happening to me randomly after the audio worked previously.

**Comment by MinusMix** [comment]
> Were you able to find a fix? I am experiencing the same issue whenever audio from the experience plays. It started happening to me randomly after the audio worked previously.

Nope, cant find a fix to it even after 2 months

**Comment by asdffeyy** [comment]
Still happening.

**Comment by Alxhr0** [comment]
Happening for me as well

**Comment by vaariable** [comment]
still happening for me

**Comment by Dumbhog** [comment]
Only happens for me when I join while being in a discord call, annoying I have to put up with it or leave the call to fix it

**Comment by SillyCricket** [comment]
> I fixed it by doing this in the terminal
> 
> export WINEPREFIX="$HOME/.local/share/vinegar/prefix"
> 
> winetricks sound=pulse (You might have to install winetricks)
> 
> Hope this helps

Thank you, I love you so much

**Comment by StarmanAkremis** [comment]
> I fixed it by doing this in the terminal
> 
> export WINEPREFIX="$HOME/.local/share/vinegar/prefix"
> 
> winetricks sound=pulse (You might have to install winetricks)
> 
> Hope this helps

that folder doesn't exist

**Comment by Dumbhog** [comment]
I managed to fix it myself a different way, turns out my headphones have a built in microphone and my os lists my headphones as two different devices, “{model} headphones” and “{model} handsfree”. When I was using discord, it switched my audio to the handsfree device and the sober audio became completely unrecognisable and the discord audio was also of poor quality. I fixed it by merely switching the device in my system audio settings. The game and discord sound quality became normal again.

**Comment by StarmanAkremis** [comment]
> I managed to fix it myself a different way, turns out my headphones have a built in microphone and my os lists my headphones as two different devices, “{model} headphones” and “{model} handsfree”. When I was using discord, it switched my audio to the handsfree device and the sober audio became completely unrecognisable and the discord audio was also of poor quality. I fixed it by merely switching the device in my system audio settings. The game and discord sound quality became normal again.

I do not have this, I use wired headphones but it still happens

**Comment by crweul** [comment]
+1

**Comment by avereyishere** [comment]
same

**Comment by Fiszh** [comment]
Still happening on 1.6.7.
Logs show FMOD invalid handle errors (``FMOD_RESULT:32``) on ``Channel::setPosition`` firing repeatedly.

```
info: Roblox: [FLog::Audio] InputDevice 0: Android audio output([ffffffff-ffff-ffff-ffffffffffffffff]) 48000/2/4
info: Roblox: [FLog::FMOD] FMOD API error, FMOD_RESULT:32, instance:0x4620021, functionname:Channel::setPosition, functionparams:14581, 2
info: Roblox: [FLog::FMOD] FMOD API error, FMOD_RESULT:32, instance:0x4740151, functionname:Channel::setPosition, functionparams:14581, 2
info: Roblox: [FLog::FMOD] FMOD API error, FMOD_RESULT:32, instance:0x46a00d5, functionname:Channel::setPosition, functionparams:14581, 2
info: Roblox: [FLog::FMOD] FMOD API error, FMOD_RESULT:32, instance:0x4620121, functionname:Channel::setPosition, functionparams:14581, 2
info: Roblox: [FLog::FMOD] FMOD API error, FMOD_RESULT:32, instance:0x4740331, functionname:Channel::setPosition, functionparams:14581, 2
```

**Comment by kunefewastakenn** [comment]
it happens when i play neighbours and other microphone games. The rest of systems audio stays the same.

**Comment by Noellelivinggayness** [comment]
I can confirm the same behavior on Arch linux KDE Pipewire

**Comment by Noellelivinggayness** [comment]
basically sounds from hell

**Comment by desh0cc** [comment]
It seems to me like the issue isn't tied to any specific game but it happens in any game with a lot of players in voice chat. One thing I noticed: if I disconnect from voice chat in settings and rejoin the same lobby the audio goes back to normal, so I don't think it's driver-related. I've also tried switching between different sound servers `to ALSA -> to PULSE -> to PIPEWIRE` but it had zero effect. 

It also doesn't happen for me on the smaller servers (under ~30 players, for example in neighbors), when the sound stays completely normal under that conditions, but it start going abysmally hellish above some kind of specific threshold that can actually be noticed in real-time while you're talking to someone.

My best guess is that it's something to do with how sober handles a large number of concurrent voice chat streams, but I could be wrong

**Comment by StarmanAkremis** [comment]
> It seems to me like the issue isn't tied to any specific game but it happens in any game with a lot of players in voice chat. One thing I noticed: if I disconnect from voice chat in settings and rejoin the same lobby the audio goes back to normal, so I don't think it's driver-related. I've also tried switching between different sound servers `to ALSA -> to PULSE -> to PIPEWIRE` but it had zero effect. 
> 
> It also doesn't happen for me on the smaller servers (under ~30 players, for example in neighbors), when the sound stays completely normal under that conditions, but it start going abysmally hellish above some kind of specific threshold that can actually be noticed in real-time while you're talking to someone.
> 
> My best guess is that it's something to do with how sober handles a large number of concurrent voice chat streams, but I could be wrong

no  it has nothing to do with voice chat, it happens on some single player games like grace (mostly on reprieve)

**Comment by Noellelivinggayness** [comment]
> I managed to fix it myself a different way, turns out my headphones have a built in microphone and my os lists my headphones as two different devices, “{model} headphones” and “{model} handsfree”. When I was using discord, it switched my audio to the handsfree device and the sober audio became completely unrecognisable and the discord audio was also of poor quality. I fixed it by merely switching the device in my system audio settings. The game and discord sound quality became normal again.

I can confirm it's related to that on my machine but prior to opening sober no problem happens so it still causes something even if the fix is a system tweak

**Comment by StarmanAkremis** [comment]
> > I managed to fix it myself a different way, turns out my headphones have a built in microphone and my os lists my headphones as two different devices, “{model} headphones” and “{model} handsfree”. When I was using discord, it switched my audio to the handsfree device and the sober audio became completely unrecognisable and the discord audio was also of poor quality. I fixed it by merely switching the device in my system audio settings. The game and discord sound quality became normal again.
> 
> I can confirm it's related to that on my machine but prior to opening sober no problem happens so it still causes something even if the fix is a system tweak

"hands free" is a mode made specifically for calls, it's not a sober issue, that's just how phone calls are made.

**Comment by desh0cc** [comment]
> > It seems to me like the issue isn't tied to any specific game but it happens in any game with a lot of players in voice chat. One thing I noticed: if I disconnect from voice chat in settings and rejoin the same lobby the audio goes back to normal, so I don't think it's driver-related. I've also tried switching between different sound servers `to ALSA -> to PULSE -> to PIPEWIRE` but it had zero effect.
> > It also doesn't happen for me on the smaller servers (under ~30 players, for example in neighbors), when the sound stays completely normal under that conditions, but it start going abysmally hellish above some kind of specific threshold that can actually be noticed in real-time while you're talking to someone.
> > My best guess is that it's something to do with how sober handles a large number of concurrent voice chat streams, but I could be wrong
> 
> no it has nothing to do with voice chat, it happens on some single player games like grace (mostly on reprieve)

I decided to check and played a few rounds of reprieve and the main mode, but audio stays completely normal for me, even if the performance drops. I also didn't have issues with any other single player game so far, so perhaps we have different issues or different forms of it?

Maybe it depends on the hardware you're using?

**Comment by StarmanAkremis** [comment]
> > > It seems to me like the issue isn't tied to any specific game but it happens in any game with a lot of players in voice chat. One thing I noticed: if I disconnect from voice chat in settings and rejoin the same lobby the audio goes back to normal, so I don't think it's driver-related. I've also tried switching between different sound servers `to ALSA -> to PULSE -> to PIPEWIRE` but it had zero effect.
> > > It also doesn't happen for me on the smaller servers (under ~30 players, for example in neighbors), when the sound stays completely normal under that conditions, but it start going abysmally hellish above some kind of specific threshold that can actually be noticed in real-time while you're talking to someone.
> > > My best guess is that it's something to do with how sober handles a large number of concurrent voice chat streams, but I could be wrong
> > 
> > no it has nothing to do with voice chat, it happens on some single player games like grace (mostly on reprieve)
> 
> I decided to check and played a few rounds of reprieve and the main mode, but audio stays completely normal for me, even if the performance drops. I also didn't have issues with any other single player game so far, so perhaps we have different issues or different forms of it?
> 
> Maybe it depends on the hardware you're using?

I worded it wrong, I meant "also happens on single player games". On windows it works fine. maybe it's related to how linux sends audio data? do you use pipewire?

**Comment by Noellelivinggayness** [comment]
> > > I managed to fix it myself a different way, turns out my headphones have a built in microphone and my os lists my headphones as two different devices, “{model} headphones” and “{model} handsfree”. When I was using discord, it switched my audio to the handsfree device and the sober audio became completely unrecognisable and the discord audio was also of poor quality. I fixed it by merely switching the device in my system audio settings. The game and discord sound quality became normal again.
> > 
> > 
> > I can confirm it's related to that on my machine but prior to opening sober no problem happens so it still causes something even if the fix is a system tweak
> 
> "hands free" is a mode made specifically for calls, it's not a sober issue, that's just how phone calls are made.

why should it make roblox's soundscape sound like hell? and I doubt it's related to that cause it's not the discord call that causes this this happens ONLY if sober is open and I have my headset connected with Bluetooth (It has output and input on the same device) but it does NOT happen if any of the following are met: roblox is closed, the headset is connected through cable (only has output on the device), the headset's mic is removed with a command

**Comment by avereyishere** [comment]
this happens whenever you're using a MONO sound output from my checks.

**Comment by gityy9** [comment]
still happening for me bro its so annoying the constant audio glitches i even tried headphones same results in all games it happens but in windows the sound is completely normal DEVICE SPECS: i5 3550s rx 5502gb 16gb ram 1tb hardrive  and the reason i dont use windows a lot is the performance there seems to be worse over time maybe becoz of bloat so i tried sober works great but then there this issue and for some reason didnt use to happen before on zorin os 18.1 same version now it happens dont know why. EDIT: suddenly the glitching stopped got fixed after updating sober just today zorin os 18.1 Edit: NOW THE APP CLOSES on startup the only way to make it work is by launching games through the web and it makes it so i cant open the app gpu screen recorder idk whats this weird issue with logging us out am on wayland :( edit: audio cracking back again after doing sudo apt update and upgrade

**Comment by Dumbhog** [comment]
> I managed to fix it myself a different way, turns out my headphones have a built in microphone and my os lists my headphones as two different devices, “{model} headphones” and “{model} handsfree”. When I was using discord, it switched my audio to the handsfree device and the sober audio became completely unrecognisable and the discord audio was also of poor quality. I fixed it by merely switching the device in my system audio settings. The game and discord sound quality became normal again.

To elaborate on my comments, I have switched to Cachy Os and the problem has disappeared altogether, but I can now describe more in detail due to the way it handles bluetooth audio. There is no longer two different "devices" on Cachy but I can use my headphones in two different types of codecs: "headset unit" codecs ,which is used when you are on a call with the built in microphone (lowers audio quality significantly to allow headroom for input data, I assume) and "high fidelity playback codecs" - The normal ones. By using a dedicated microphone, I can both not have these issues and also have normal audio quality while on call at the same time, because I can always be on the high fidelity codecs. Maybe to those who are experiencing issues make sure you are on the right codec? I think I was the only (recorded) one who was facing this issue exclusively while on call however.

**Comment by Noellelivinggayness** [comment]
> To elaborate on my comments, I have switched to Cachy Os and the problem has disappeared altogether, but I can now describe more in detail due to the way it handles bluetooth audio. There is no longer two different "devices" on Cachy but I can use my headphones in two different types of codecs: "headset unit" codecs ,which is used when you are on a call with the built in microphone (lowers audio quality significantly to allow headroom for input data, I assume) and "high fidelity playback codecs" - The normal ones. By using a dedicated microphone, I can both not have these issues and also have normal audio quality while on call at the same time, because I can always be on the high fidelity codecs. Maybe to those who are experiencing issues make sure you are on the right codec? I think I was the only (recorded) one who was facing this issue exclusively while on call however.

I couldn't replicate it as of recently but I think I only had it while on call but I couldn't say cause it only happened when I was on a call and now even on calls it doesn't happen anymore I am had the issue on cachyos

**Comment by dashiellbenton** [comment]
> I fixed it by doing this in the terminal
> 
> export WINEPREFIX="$HOME/.local/share/vinegar/prefix"
> 
> winetricks sound=pulse (You might have to install winetricks)
> 
> Hope this helps

It used to work. Now it does not. what do i even do at this point, im on cachyos, kde plasma, and it doesnt work with any audio device

**Comment by StarmanAkremis** [comment]
Some people here are complaining about some bluetooth thing, that's not a sober issue, bluetooth headphones ususally have 2 modes, one for normal hearing and another for calls, because calls use a different audio codec, sometimes the computer uses the call mode instead of the normal mode, that's not a sober issue, that's a system configuration issue.

**Comment by fr0stlol** [comment]
> Some people here are complaining about some bluetooth thing, that's not a sober issue, bluetooth headphones ususally have 2 modes, one for normal hearing and another for calls, because calls use a different audio codec, sometimes the computer uses the call mode instead of the normal mode, that's not a sober issue, that's a system configuration issue.

It's specifically with sober tho, try any different Soo or game and it's fine

**Comment by StarmanAkremis** [comment]
> > Some people here are complaining about some bluetooth thing, that's not a sober issue, bluetooth headphones ususally have 2 modes, one for normal hearing and another for calls, because calls use a different audio codec, sometimes the computer uses the call mode instead of the normal mode, that's not a sober issue, that's a system configuration issue.
> 
> It's specifically with sober tho, try any different Soo or game and it's fine

my guess is roblox's voice chat enables that mode

**Comment by RoaringMantis** [comment]
ello fellas, i have found a fix that works for me. using pulsemeter audio i channel sobers application output to a virtual input which i select to have stereo rather than mono audio option. if you have sober running whilst doing this close it then restart. then have your virtual output go to a hardware output and it should work. for me it works with speakers, bluetooth or anything

my final verdict is that sober somehow just messes up the mono audio output
feel free to ask me questions if it doesnt work for you

cheers gentlemen
